spring:
  application:
    name: base_spring_boot
  datasource:
    url: jdbc:mysql://localhost:3306/base_core?createDatabaseIfNotExist=true
    username: root
    password: Giadat9898@
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
jwt:
  secret:
    key: 3b6f9c1d8a7e4f2b5c9d7a8e6f3b1c4d7e9f2a1b4c6d8e7f9a2c5b7d9f1e3a6b
  expired:
    access: 864000

